quarkus:
  jackson:
    timezone: America/Lima

  hibernate-orm:
    database:
      generation: none
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    log:
      sql: true

  datasource:
    db-kind: postgresql
    jdbc:
      url: 'jdbc:postgresql://34.176.222.51:5432/qaliwarma'
    username: postgres
    password: e|S&&gYp~S9?R@cH